# Docs2Synth Configuration File

# Data folder settings - where to save all files
data:
  # Root data directory
  root_dir: ./data

  # Downloaded datasets
  datasets_dir: ./data/datasets

  # Processed data outputs
  processed_dir: ./data/processed

  # QA pairs
  qa_pairs_dir: ./data/qa_pairs

  # Models
  models_dir: ./models

  # Logs
  logs_dir: ./logs

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO

  # Log format: simple, default, detailed
  format: default

  # Console logging
  console:
    enabled: true
    level: INFO

  # File logging
  file:
    enabled: true
    path: ./logs/docs2synth.log
    level: DEBUG
    max_bytes: 10485760  # 10MB
    backup_count: 5
    use_timestamp: false  # If true, adds timestamp to filename (e.g., docs2synth_20251010_232045.log)

  # Third-party library log levels
  third_party:
    level: WARNING
    loggers:
      - urllib3
      - requests
      - transformers
      - torch
      - tensorflow
      - PIL
      - matplotlib
      - openai
